.vscode/settings.json, user_login.php
i am adding here a password complexity that password must be 8 character
=> password complexity

index.html
I have applied scroll animations in your website , i hope you will like it :)
=> I have made your website look dynamic :)

vendor/add_menu.php, vendor/edit_menu.php, vendor/home.php
I have Fixed issue #34
Closes: #
I have changed color and font on the Vendor's page and  Add search functionality  and add back button on edit.php and add_menu.php
=> Change UI for Vendor's Home Page

readme.md
I have added all the contributors in readme.md file to give them appreciation.
Completed #36 
@Vimall03  please review and accept
Closes: #36
=> Additon of All Contributors | Issue #36

index.html
I fixed the padth of the image in src of logo 
Issue no : #50 
Closes: #50
=> logo bug fixed

darkMode.js, index.html, main.css
https://github.com/user-attachments/assets/4297699c-6378-46db-8388-7c093a3fc7dd
closes #54
=> dark mode added✨

index.html, main.css, menu.php, pin_search.php, track_order.php
closes #56 
https://github.com/user-attachments/assets/83b9e804-78f6-47fe-820e-2b2c322a4117
- added the backend logic.
- fixed the text of the homepage and dark mode UI. 
- Since most of the files were in php i tried added the logic , i never worked with them so ive tried to fix something. Have a look.
=> fixed the dark mode issue and issue#56

Contribution.md
I want to add contribution.md 
we can tell the contributors how to do the contribution
closes #21
=> Add contribution.md

email_verify.php, main.css, user_login.php, user_signup.php
Password validation is now performed during user registration on the User Signup page. A "show password" feature has been added for easier password verification. After registration, users are redirected directly to the home page without needing to log in again. Additionally, the User Signup and User Login pages are no longer accessible once the user is logged in.
Closes: #62 
Demo:
https://github.com/user-attachments/assets/2426e4cb-c675-40a5-a04b-0e2d8c3657eb
=> Fix reg/login validation

readme.md
I have made the following enhancements to the README:
- Added a graphical line to clearly distinguish between sections.
- Introduced a "Star this repo" section to encourage more users to support the project.
- Added a metrics table to display the number of open issues, pull requests, stars, and forks.
These changes are intended to improve the layout and provide better insights into the repository's activity.
Kindly merge these and assign me labels @Vimall03 
Thank you :)
=> Enhanced README with Graphics Divider, Star Section, and Metrics Table

email_verify.php
=> Fixed the Bug

index.html
@Vimall03 
i have added scroll to top feature, kindly check it out
https://github.com/user-attachments/assets/0f73fc7b-c4a9-44ee-814c-069a7604bce3
=> added scroll to top

index.html
@Vimall03 
I have enhanced the contact us section
this is old one
this is the new one
=> enhanced contact us

new_track_order.css, new_track_order.php, verify.php
Redesigned the track_order.php page. It is now more approaching in terms of readability and responsiveness. 
Redesigned the navbar considering a part of this page. Ensured for a smooth navigation while redesigning the navbar. Navbar is also responsive.
Closes: #96 
Following tests have been perfomed:
=> New track order page

index.html, main.css
🛡️Issue Fixed #79 
Added a FAQ section that would improve customer support efficiency and reduce repetitive inquiries. It would also help new customers quickly find relevant information.
=> Added: FAQ Section

styles.css, vendor/add_menu.php, vendor/edit_menu.php, vendor/home.php, vendor/partials/_dbconnect.php
fixes #44 
Closes: #44 
home page:
add item page:
edit page:
Additional changes ** Also resolved bug where logout button was not working properly **
=> enhanced vendor ui

contributors/contributor.css, contributors/contributor.html, contributors/contributor.js, index.html
the contributors page has been added,
https://github.com/user-attachments/assets/c36d098b-1994-426e-a3b9-439a966dd20f
issue #91 solved. @Vimall03 can you please review this , thank you!
=> ✨contributors page added.✨

edit_profile.php, email_verify.php, home.php, index.html, menu.php, new_track_order.php, order_success.php, orders.php, pin_search.php, profile.php, track_order.php, user_login.php, user_signup.php
the system is working, @Vimall03 can you please review this .
#123 solved.
https://github.com/user-attachments/assets/af1ea0b8-149d-40f9-a32d-cd90a15ff9e2
Closes: #123 solved
=> multi language support system added.

.github/workflows/pr-checker.yml
Closes #135
This workflow ensures that every pull request description includes an associated issue number for better tracking and clarity. If the required format is not met, contributors will receive clear feedback on how to correct it.
- **Error Case** 
**When the PR description does not meet the required format (missing the issue reference):**
The PR description should include the issue number assigned to you. ⚠️
##[error]An issue reference like 'Fixed #<issue-number>' must be included in the description.
- **Success** 
PR description is valid.
All checks passed.
@Vimall03 please assign all the labels given at issue #135
=> Added pr-checker

change_password.php, checkout.php, edit_profile.php, home.php, index.php, main.css, menu.php, new_track_order.php, orders.php, output.css, profile.php
=> Revert "changed navbar design"

home.php, index.php, menu.js, new_track_order.css, new_track_order.php, output.css, pin_search.php, profile.php
=> Revert "Uniform navbar and nav bug fixes"

change_password.php, checkout.php, edit_profile.php, home.php, index.php, main.css, menu.js, menu.php, new_track_order.php, orders.php, output.css, partials/_dbconnect.php, pin_search.php, profile.php, track_order.php, vendor/add_menu.php, vendor/edit_menu.php, vendor/home.php, vendor/partials/_dbconnect.php
I have tried to covered all the pages. They are listed below
- orders
- home.php
- index
- profile
- change password
- edit password
- vendor/home
- add menu
- edit menu
- menu
- checkout
- pin search
- track order
- new track order
Closes: #142 
Related PR: #153
=> Navbar same on all pages!

readme.md
Added Stargazers and Forkers section to readme.md
- [ x] Documentation update
Fixes #162 
Closes: #162 
- [x ] I have tested my changes and ensured they work as expected.
- [ x] I have added necessary documentation (if applicable).
- [ x] I have reviewed my code for style and linting issues.
- [ x] I have ensured that any dependent changes are merged before this PR.
=> Update readme.md Added Stargazers and Forkers section to readme.md

contributors/contributor.css, contributors/contributor.html, index.php
I add the page of contributors
- [✔ ] Bug fix
- [✔ ] Documentation update
Closes: #163 
- [✔ ] I have tested my changes and ensured they work as expected.
- [✔ ] I have added necessary documentation (if applicable).
- [✔ ] I have reviewed my code for style and linting issues.
- [✔ ] I have ensured that any dependent changes are merged before this PR.
=> there is no any contributors page (Issue #163)

recommendation-system/recommendation_system.php, recommendation-system/recommendations.php
=> [FEAT] : Implement Personalized Dish and Vendor Recommendations

Project Strucrure.md
I have added the Project Structure.md a seperate file. This guides contributors on where specific files and folders are located and what they contain.
Closes: #176
**Note:** @Vimall03  please make sure to add all necessary labels in #176
=> Create Project Strucrure.md

alimento-nextjs/actions/customer/customerDELETE.tsx, alimento-nextjs/actions/customer/customerEDIT.tsx, alimento-nextjs/actions/customer/customerGET.tsx, alimento-nextjs/actions/customer/login-action.tsx, alimento-nextjs/actions/customer/signup-action.tsx
This pull request addresses the need for robust server-side actions to manage customer data, including creating, reading, updating, and deleting customer records in the database. Each action is implemented with comprehensive error handling to address potential issues, such as database connectivity problems, invalid data, or permission-related errors. This setup ensures the reliability and security of customer data management.
- Adds a new customer to the database.
- Validates all required fields to prevent incomplete data entry.
- Retrieves customer information based on a unique identifier (e.g., customer ID).
- Supports optional filtering to refine customer data retrieval.
- Modifies existing customer data with the provided information.
- Includes validation checks to ensure updates are …
=> Implement Server Actions for Customer CRUD Operations with Error Handling

user_login.php, user_signup.php
Description: 
Added login and sign-in functionality with an integrated "Sign in with Google" option to enhance user convenience. This update includes a Google OAuth button styled for seamless visual integration, located below the main login button on the sign-in page. The Google sign-in redirects users to Google’s authentication flow and returns them to the application upon successful login, enabling quicker access for users with Google accounts.
<!-- Please mention the issue that this PR addresses by using a keyword like "Fixes #issuenumber" or "Closes #issuenumber". Example: Closes #171 
Closes: #171
- [] I have added necessary documentation (if applicable).
I hope that the contribution made is substantial!
=> Added a login and sign-in button with google option

alimento-nextjs/app/api/testing/vendor/[vendorId]/route.ts, alimento-nextjs/app/api/testing/vendor/route.ts
This pull request introduces a set of API endpoints to facilitate the testing and management of vendor CRUD operations. These endpoints enable easy interaction with vendor data and can serve as a foundation for third-party integrations, allowing collaborators to perform Create, Read, Update, and Delete operations on vendor records.
These endpoints are designed with testing in mind, allowing thorough validation of the server-side actions and error handling. By exposing these endpoints, we provide a reliable interface for development, testing, and potential integration with external services.
- Adds a new vendor to the database.
- Validates all required fields, such as `name` and `email`, to ensure data completeness.
- Returns the newly created vendor record or an error message if …
=>  Implement Vendor CRUD API Endpoints for Testing and 3rd Party Integration

alimento-nextjs/actions/customer/customerDELETE.tsx, alimento-nextjs/actions/customer/customerEDIT.tsx, alimento-nextjs/actions/customer/customerGET.tsx, alimento-nextjs/actions/customer/login-action.tsx, alimento-nextjs/actions/customer/signup-action.tsx, alimento-nextjs/app/api/testing/customer/[customerId]/route.ts, alimento-nextjs/app/api/testing/customer/route.ts
This pull request introduces a set of API endpoints to facilitate the testing and management of customer CRUD operations. These endpoints enable easy interaction with customer data and can serve as a foundation for third-party integrations, allowing collaborators to perform Create, Read, Update, and Delete operations on customer records.
These endpoints are designed with testing in mind, allowing thorough validation of the server-side actions and error handling. By exposing these endpoints, we provide a reliable interface for development, testing, and potential integration with external services.
- Adds a new customer to the database.
- Validates all required fields, such as `name` and `email`, to ensure data completeness.
- Returns the newly created customer record or an error message if …
=> Implement Customer CRUD API Endpoints for Testing and 3rd Party Integration

alimento-nextjs/actions/customer/customerDELETE.tsx, alimento-nextjs/actions/customer/customerEDIT.tsx, alimento-nextjs/actions/customer/customerGET.tsx, alimento-nextjs/actions/customer/login-action.tsx, alimento-nextjs/actions/customer/signup-action.tsx, alimento-nextjs/actions/dish/dishCREATE.ts, alimento-nextjs/actions/dish/dishDELETE.ts, alimento-nextjs/actions/dish/dishEDIT.ts, alimento-nextjs/actions/dish/dishGET.ts, alimento-nextjs/actions/dish/dishGETALL.ts, alimento-nextjs/app/api/testing/customer/[customerId]/route.ts, alimento-nextjs/app/api/testing/customer/route.ts, alimento-nextjs/prisma/schema.prisma
This pull request introduces a comprehensive schema for the `Dish` model in the database, enhancing the management of dishes by vendors in the application. The schema includes enums for categories and tags, providing a structured way to classify dishes according to their type and dietary considerations. Additionally, CRUD operations have been implemented, allowing for the creation, reading, updating, and deletion of dishes, as well as a method to retrieve all dishes with optional filtering capabilities based on tags and categories.
- **ID**: A unique identifier for each dish, automatically generated as a UUID.
- **Name**: The name of the dish.
- **Description**: An optional field that provides additional information about the dish.
- **Price**: A float representing the cost of the dish.
- …
=>  Implement Dish Schema with Tags and Enum Categories, along with CRUD Operations and Filtering

alimento-nextjs/actions/customer/customerDELETE.tsx, alimento-nextjs/actions/customer/customerEDIT.tsx, alimento-nextjs/actions/customer/customerGET.tsx, alimento-nextjs/actions/customer/login-action.tsx, alimento-nextjs/actions/customer/signup-action.tsx, alimento-nextjs/actions/dish/dishCREATE.ts, alimento-nextjs/actions/dish/dishDELETE.ts, alimento-nextjs/actions/dish/dishEDIT.ts, alimento-nextjs/actions/dish/dishGET.ts, alimento-nextjs/actions/dish/dishGETALL.ts, alimento-nextjs/app/api/testing/customer/[customerId]/route.ts, alimento-nextjs/app/api/testing/customer/route.ts, alimento-nextjs/app/api/testing/dish/[vendorId]/[dishId]/route.ts, alimento-nextjs/app/api/testing/dish/route.ts, alimento-nextjs/prisma/schema.prisma
This pull request introduces a set of API endpoints for managing dishes in the application. The endpoints facilitate the creation, retrieval, updating, and deletion of dish records while allowing vendors to manage their dishes efficiently. The routes are designed to support filtering and interaction with the dish data, thereby enhancing the overall functionality of the application.
- This endpoint allows vendors to create a new dish entry in the database.
- It requires the following fields:
- `name`: The name of the dish (string).
- `description`: A brief description of the dish (optional).
- `price`: The price of the dish (float).
- `category`: The category of the dish (enum).
- `tags`: An array of tags related to the dish (array of enums).
- `vendorId`: The unique identifier of the …
=> Dishes API for Testing and Route Availability

alimento-nextjs/app/(PublicRoutes)/contributors/page.tsx
=> Migrate Contributors page to Next.js

alimento-nextjs/app/(PublicRoutes)/restaurant/page.tsx
=> Migrate and Implemented Resturant page to Next.js 

alimento-nextjs/app/(PublicRoutes)/Auth/Customer/SignIn/page.tsx, alimento-nextjs/app/(PublicRoutes)/Auth/Customer/SignUp/page.tsx, alimento-nextjs/app/(PublicRoutes)/auth/Vendor/SignIn/page.tsx, alimento-nextjs/app/(PublicRoutes)/auth/Vendor/SignUp/page.tsx, alimento-nextjs/app/(PublicRoutes)/auth/components/otpForm.tsx, alimento-nextjs/components/common/navbar-actions.tsx
This PR addresses the backend and frontend modifications required to complete and refine the authentication flow for vendors and customers. It ensures all links are correct, fully integrates the authentication and OTP processes, and thoroughly tests the user experience for a seamless sign-up/login journey.
1. **Backend Logic Modifications**: 
- Added necessary logic to support the OTP generation and verification process, enabling secure and reliable user authentication.
- Adjusted link handling on the backend to ensure the sign-up and login flow directs users based on their role (vendor or customer).
2. **Frontend Logic Modifications**:
- Corrected and updated all links in the sign-up/login flows to point to the proper destinations for vendors and customers.
- Updated the navbar login …
=> auth is now functional

alimento-nextjs/actions/customer-dash/customerVendorData.tsx, alimento-nextjs/actions/customer-dash/customerVendorOrderHistory.tsx, alimento-nextjs/prisma/schema.prisma
fix: #247
- Added backend functionality to fetch customer-specific order history.
- Implemented new API route to retrieve order details for the customer dashboard.
- Included order status, total amount, and associated vendor details in the response.
- Created a `getCustomerOrderHistory` function in the backend to fetch orders based on `customerId`.
- Added API route `/api/orders/customer-history` to handle GET requests for fetching order history.
- Ensured that the order data includes customer and vendor information.
- Verified API endpoint for various customer accounts.
- Confirmed accurate order data retrieval and error handling.
```typescript
const response = await getCustomerVendorData();
console.log(response);
Closes #247
=>  Implement Order History View for Customer Dashboard [Backend + Routes]

alimento-nextjs/actions/customer-dash/customerVendorData.tsx, alimento-nextjs/actions/customer-dash/customerVendorOrderHistory.tsx, alimento-nextjs/actions/customer-ticket/README.md, alimento-nextjs/actions/customer-ticket/createTicket.tsx, alimento-nextjs/prisma/schema.prisma
fix: #272 
We need to implement a Ticketing System API that allows customers to raise, manage, and track their support tickets. The API should support the following operations:
1. **Create a Ticket**: Allows customers to create a new support ticket with a title and description of the issue.
2. **Get Customer Tickets**: Retrieves a list of all tickets raised by a specific customer.
3. **Update Ticket Status**: Allows updating the status of a ticket (e.g., "PENDING", "IN_PROGRESS", "RESOLVED", "CLOSED").
4. **Delete a Ticket**: Enables customers or support agents to delete a ticket.
---
- **POST** `/api/ticket`: Raise a new ticket.
- **GET** `/api/ticket/{customerId}`: Fetch all tickets for a given customer.
- **PATCH** `/api/ticket/{ticketId}`: Update the status of a ticket.
- **DELETE** …
=> Implement Ticketing System API for Customer Support

alimento-nextjs/actions/Chat/createChat.ts, alimento-nextjs/actions/Chat/deleteMessage.ts, alimento-nextjs/actions/Chat/editMessage.ts, alimento-nextjs/actions/Chat/getAllChatBySeller.ts, alimento-nextjs/actions/Chat/getAllChatByUserId.ts, alimento-nextjs/actions/Chat/getSpecificChat.ts, alimento-nextjs/prisma/schema.prisma
This pull request introduces chat and message management features, enabling customers and vendors to communicate within the application. These changes include functions for creating, fetching, editing, and deleting messages and chats, alongside necessary schema updates in Prisma for chat and message relationships.
1. **Chat Functionality**:
- Implemented `createChat` function to initialize a new chat between a customer and a vendor, with an initial message.
- Added `getAllChatsByVendorId` and `getAllChatsByCustomerId` functions to retrieve all chats for a specific vendor or customer.
- Developed `getSpecificChat` function to fetch a unique chat between a customer and a vendor for a particular dish.
2. **Message Management**:
- Created `deleteMessage` function to allow users to delete …
=> added backend routes for chat and database schema for chat feature
